#!/bin/sh

export PATH=@PATH@

# Stop all init scripts in /etc/init.d
# executing them in reversed numerical order.
for i in $(ls -r /etc/init.d/S??*) ;do
	[ ! -f "$i" -o ! -x "$i" ] && continue
	$i stop
done

# Turn off back light on rpi touchscreen
if [ -f /sys/class/backlight/rpi_backlight/bl_power ]; then
	echo 1 > /sys/class/backlight/rpi_backlight/bl_power
fi

killall5 -15 -o 1
sleep 2
sync
killall5 -9 -o 1
sleep 2
sync
swapoff -a
umount -a -r
mount -o remount,ro /
