#!/bin/sh

export PATH=@PATH@

echo
echo
echo "The system is shutting down ..."

# Stop all init scripts in /etc/init.d
# executing them in reversed numerical order.
#
for i in $(ls -r /etc/init.d/S??*) ;do
     [ ! -f "$i" ] && continue
     [ ! -x "$i" ] && continue

     case "$i" in
	*.sh)
	    # Source shell script for speed.
	    (
		trap - INT QUIT TSTP
		set stop
		. $i
	    )
	    ;;
	*)
	    # No sh extension, so fork subprocess.
	    $i stop
	    ;;
    esac
done

echo "Sending SIGTERM to all processes ..."
killall5 -15 -o 1

sleep 2

echo "Sending SIGKILL to all processes ..."
killall5 -9 -o 1

echo "Syncing filesystems ..."
sync

# Turn off backlight if we are connected to rpi touchscreen
if [ -f /sys/class/backlight/rpi_backlight/bl_power ]; then
	echo 1 > /sys/class/backlight/rpi_backlight/bl_power
fi

echo "Unmounting filesystems ..."
umount -a -r
