#!/bin/sh

PRETTY_NAME="Buildroot"
[ -r /etc/os-release ] && . /etc/os-release

# Set path used for startup scripts
export PATH=@PATH@

# Limit kernel messages on console
dmesg -n 1

# Set user mask for startup scripts
umask 0002

echo "Starting $PRETTY_NAME"
echo

mount -t proc proc /proc
mkdir -p /dev/pts
mkdir -p /dev/shm

# Start all init scripts in /etc/init.d
# executing them in numerical order.
for i in /etc/init.d/S??* ;do
     [ ! -f "$i" ] && continue
     [ ! -x "$i" ] && continue

     case "$i" in
	*.sh)
	    # Source shell script for speed.
	    (
		trap - INT QUIT TSTP
		set start
		. $i
	    )
	    ;;
	*)
	    # No sh extension, so fork subprocess.
	    $i start
	    ;;
    esac
done

[ -x "/etc/rc.local" ] && /etc/rc.local

[ -x "/usr/bin/psplash-write" ] && /usr/bin/psplash-write "QUIT"
