#!/bin/sh
#
# fsck
#

NAME="fsck"
EXEC="$(which $NAME)"
ARGS="-A -P -T -y"

[ -x "$EXEC" ] || exit 0

. /etc/init.d/functions

check_root

start() {
	log_message "Checking filesystems ...\n"
	$EXEC $ARGS >> /run/bootlog
	RETVAL=$?
	if [ $(($RETVAL & 2)) -ne 0 ]; then
		sleep 5
		reboot -f
		exit 0
	fi
}

stop() {
	:
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  *)
	echo "Usage: $0 {start|stop}" >&2
	exit 1
	;;
esac
