#!/usr/bin/bash
#
# mount
#

. /etc/init.d/functions

check_root

start() {
	log_message "Mounting file systems ... "
	mount -a
	check_status
}

stop() {
	:
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  *)
	echo "Usage: $0 {start|stop}" >&2
	exit 1
	;;
esac
