#!/usr/bin/bash
#
# hostname
#

. /etc/init.d/functions

check_root

start() {
	log_message "Setting hostname ... "
	hostname -F /etc/hostname >/dev/null 2>&1
	check_status
}

stop() {
	:
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  *)
	echo "Usage: $0 {start|stop}" >&2
	exit 1
	;;
esac
