#!/usr/bin/bash
#
# remount
#

. /etc/init.d/functions

[ -r "/etc/default/rootmount" ] && . "/etc/default/rootmount"

check_root

start() {
	log_message "Remounting rootfs read/write ... "
	if [ -z "$MOUNTOPTS" ]; then
		mount -o remount,rw /
	else
		mount -o remount,rw,$MOUNTOPTS /
	fi
	check_status
}

stop() {
	:
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  *)
	echo "Usage: $0 {start|stop}" >&2
	exit 1
	;;
esac
