#!/bin/sh
#
# swapfile
#

. /etc/init.d/functions

SWAPFILE=/etc/swapfile
SWAPSIZE=100

start() {
	if [ ! -f "$SWAPFILE" ]; then
		# check for read only file system
		touch $SWAPFILE 2>/dev/null || exit 0

		printf "Creating swap file ... "
		dd if=/dev/zero of=$SWAPFILE bs=1M count=$SWAPSIZE > /dev/null 2>&1 || (status_fail && exit 1)
		chmod 0600 $SWAPFILE > /dev/null 2>&1 || (status_fail && exit 1)
		mkswap $SWAPFILE > /dev/null 2>&1 || (status_fail && exit 1)
		status_ok
	fi
	printf "Activating swap file ... "
	swapon $SWAPFILE > /dev/null 2>&1
	check_status
}

stop() {
	printf "Deactivating swap file ... "
	swapoff -a > /dev/null 2>&1
	check_status
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  *)
	echo "Usage: $0 {start|stop}" >&2
	exit 1
	;;
esac
