#!/bin/sh
#
# swapfile
#

NAME="swapfile"
SWAPFILE="/etc/swapfile"
SWAPSIZE=100

# shellcheck source=/dev/null
[ -r "/etc/default/$NAME" ] && . "/etc/default/$NAME"

. /etc/init.d/functions

start() {
	if [ ! -f "$SWAPFILE" ]; then
		# check for read only file system
		touch $SWAPFILE 2>/dev/null || exit 0

		printf "Creating $NAME ... "
		dd if=/dev/zero of=$SWAPFILE bs=1M count=$SWAPSIZE > /dev/null 2>&1 || (status_fail && exit 1)
		chmod 0600 $SWAPFILE > /dev/null 2>&1 || (status_fail && exit 1)
		mkswap $SWAPFILE > /dev/null 2>&1 || (status_fail && exit 1)
		status_ok
	else
		# check for read only file system
		touch $SWAPFILE 2>/dev/null || exit 0
	fi

	printf "Activating $NAME ... "
	swapon $SWAPFILE > /dev/null 2>&1
	check_status
}

stop() {
	printf "Deactivating $NAME ... "
	swapoff -a > /dev/null 2>&1
	check_status
}

restart() {
	stop
	rm -f $SWAPFILE
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop}" >&2
	exit 1
	;;
esac
