#!/bin/sh
#
# modules
#

EXEC="$(which modprobe)"
MODS="/etc/modules.conf"

[ -x "$EXEC" ] || exit 0
[ -e "/proc/modules" ] || exit 0
[ -r "$MODS" ] || exit 0
egrep -qv '^($|#)' $MODS || exit 0

. /etc/init.d/functions

check_root

start() {
	FAIL="no"
	log_message "Loading kernel modules ... "
	while read module args; do
		case "$module" in
			""|"#"*) continue ;;
		esac
		$EXEC $module $args >/dev/null 2>&1
		if [ $? != "0" ]; then
			FAIL="yes"
		fi
	done < "$MODS"
	[ $FAIL = "yes" ] && status_fail || status_ok
}

stop() {
	:
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  *)
	echo "Usage: $0 {start|stop}" >&2
	exit 1
esac

