#!/bin/sh
#
# sysctl
#

EXEC="$(which sysctl)"

[ -x "$EXEC" ] || exit 0

. /etc/init.d/functions

check_root

start() {
	log_message "Configuring kernel parameters ... "
	$EXEC --system >/dev/null 2>&1
	check_status
}

stop() {
	:
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  *)
	echo "Usage: $0 {start|stop}" >&2
	exit 1
	;;
esac
