#!/bin/sh
#
# Start logging
#

SYSLOGD_BIN=$(which syslogd)
SYSLOGD_ARGS="-m 0"
SYSLOGD_PID="/var/run/syslogd.pid"

KLOGD_BIN=$(which klogd)
KLOGD_ARGS=""
KLOGD_PID="/var/run/klogd.pid"

[ -x "$SYSLOGD_BIN" ] || exit 0
[ -x "$KLOGD_BIN" ] || exit 0

[ -r /etc/default/logging ] && . /etc/default/logging

. /etc/init.d/functions

start() {
	printf "Starting syslogd ... "
	$SYSLOGD_BIN $SYSLOGD_ARGS
	check_status
	printf "Starting klogd ... "
	$KLOGD_BIN $KLOGD_ARGS
	check_status
}

stop() {
	printf "Stopping klogd ... "
	[ -f "$KLOGD_PID" ] && kill `cat "$KLOGD_PID"`
	check_status
	printf "Stopping syslogd ... "
	[ -f "$SYSLOGD_PID" ] && kill `cat "$SYSLOGD_PID"`
	check_status
}

restart() {
	stop
	sleep 1
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac
