#!/bin/sh
#
# swapfile
#

SWAPFILE_ENABLED=1
SWAPFILE="/var/swapfile"
SWAPSIZE=1000

[ -r "/etc/default/swap" ] && . "/etc/default/swap"

. /usr/share/rcinit/functions

check_root

start() {
	if [ "$SWAPFILE_ENABLED" -eq 1 ]; then
		if [ ! -f "$SWAPFILE" ]; then
			# check for read only file system
			touch $SWAPFILE 2>/dev/null || exit 0

			log_message "Creating swapfile ... "
			dd if=/dev/zero of=$SWAPFILE bs=1M count=$SWAPSIZE >/dev/null 2>&1 || (status_fail && exit 1)
			chmod 0600 $SWAPFILE >/dev/null 2>&1 || (status_fail && exit 1)
			mkswap $SWAPFILE >/dev/null 2>&1 || (status_fail && exit 1)
			status_ok
		else
			# check for read only file system
			touch $SWAPFILE 2>/dev/null || exit 0
		fi
		log_message "Activating swapfile ... "
		swapon $SWAPFILE >/dev/null 2>&1
		check_status
	else
		log_message "Activating swap ... "
		swapon -a >/dev/null 2>&1
		check_status
	fi
}

stop() {
	log_message "Deactivating swap ... "
	swapoff -a >/dev/null 2>&1
	check_status
}

restart() {
	stop
	sleep 1
	if [ "$SWAPFILE_ENABLED" -eq 1 ]; then
		rm -f $SWAPFILE
	fi
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}" >&2
	exit 1
	;;
esac
