#!/bin/sh
#
# retroflag
#

NAME=retroflag
EXEC=$(which $NAME)

[ -x "$EXEC" ] || exit 0

. /etc/init.d/functions

start() {
	printf "Starting $NAME ... "
	start-stop-daemon -S -q -x $EXEC -b --
	check_status
}

stop() {
	printf "Stopping $NAME ... "
	start-stop-daemon -K -q -n $NAME
	check_status
}

restart() {
	stop
	sleep 1
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart|reload}" >&2
	exit 1
	;;
esac

exit 0
