#!/usr/bin/bash

NAME="acpid"
EXEC="$(which $NAME)"
ARGS="-n"
PIDFILE="/run/acpid.pid"

[ -x "$EXEC" ] || exit 0

[ -r "/etc/default/$NAME" ] && . "/etc/default/$NAME"

. /etc/init.d/functions

check_root

start() {
	log_start $NAME
	$EXEC $ARGS >/dev/null 2>&1
	check_status
}

stop() {
	log_stop $NAME
	killall $NAME 2>/dev/null
	check_status
}

restart () {
	stop
	sleep 1
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}" >&2
	;;
esac
