#!/bin/sh
#
# irqbalance
#

NAME="irqbalance"
EXEC="$(which irqbalance)"
RUNDIR="/run/irqbalance"
PIDFILE="$RUNDIR/irqbalance.pid"
ARGS="--pid $PIDFILE"

[ -x "$EXEC" ] || exit 0

. /etc/init.d/functions

mkdir -p $RUNDIR 2> /dev/null

start() {
	printf "Starting $NAME ... "
	$EXEC $ARGS > /dev/null 2>&1
	check_status
}

stop() {
	printf "Stopping $NAME ... "
	killall $NAME 2> /dev/null
	check_status
}

restart() {
	stop
	sleep 1
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac
