#!/bin/sh
#
# irqbalance
#

NAME="irqbalance"
EXEC=$(which irqbalance)
ARGS=""
PIDFILE="/var/run/irqbalance.pid"

[ -x "$EXEC" ] || exit 0

. /etc/init.d/functions

start() {
	printf "Starting $NAME ... "
	$EXEC $ARGS > /dev/null 2>&1
	check_status
	pidof $NAME > $PIDFILE 2> /dev/null
}

stop() {
	printf "Stopping $NAME ... "
	[ -f "$PIDFILE" ] && kill `cat $PIDFILE` 2> /dev/null
	check_status
}

restart() {
	stop
	sleep 1
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac
