#!/bin/sh
#
# open-vm-tools
#

NAME="vmtoolsd"
EXEC=$(which $NAME)
PIDFILE="/run/vmtoolsd.pid"
ARGS="-b $PIDFILE"

[ -x "$EXEC" ] || exit 0

. /etc/init.d/functions

start() {
	printf "Starting $NAME ... "
	start-stop-daemon -S -q -p $PIDFILE \
		-x $EXEC -- $ARGS
	check_status
}

stop() {
	printf "Stopping $NAME ... "
	start-stop-daemon -K -q -p $PIDFILE
	check_status
}

restart() {
	stop
	sleep 1
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
	;;
esac
