#! /bin/sh
#
# urandom
#

. /etc/init.d/functions

check_root

start() {
	log_message "Initializing random number generator ... "
	seedrng > /dev/null 2>&1
	check_status
}

stop() {
	log_message "Saving random seed ... "
	seedrng > /dev/null 2>&1
	check_status
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  *)
	echo "Usage: urandom {start|stop}" >&2
	exit 1
	;;
esac
