#!/bin/sh
#
# hwclock
#

NAME="hwclock"
EXEC=$(which $NAME)
RTC="/dev/rtc0"

[ -x "$EXEC" ] || exit 0

[ -r "/etc/default/$NAME" ] && . "/etc/default/$NAME"

[ -e "$RTC" ] || exit 0

. /usr/share/rcinit/functions

check_root

start() {
	log_message "Setting system clock ... "
	mkdir -p /var/lib/hwclock 2>/dev/null
	$EXEC -s -u >/dev/null 2>&1
	check_status
}

stop() {
	log_message "Syncing hardware clock ... "
	$EXEC -w -u >/dev/null 2>&1
	check_status
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  *)
	echo "Usage: $0 {start|stop}" >&2
	exit 1
esac
