#!/bin/sh
#
# hciattach
#

EXEC=$(which hciattach)

[ -x "$EXEC" ] || exit 0

. /etc/init.d/functions

check_root

start() {
	printf "Initializing bluetooth adapter ..."
	$EXEC /dev/ttyAMA0 bcm43xx 921600 noflow - > /dev/null 2>&1
	check_status
}

stop() {
	:
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  *)
	echo "Usage: $0 {start|stop}" >&2
	exit 1
	;;
esac
