#!/usr/bin/bash
#
# smartd
#

NAME="smartd"
EXEC="$(which $NAME)"
PIDFILE="/run/smartd.pid"
ARGS="-i 60 -p $PIDFILE -q never"

[ -x "$EXEC" ] || exit 0

# shellcheck source=/dev/null
[ -r "/etc/default/$NAME" ] && . "/etc/default/$NAME"

. /usr/share/rcinit/functions

check_root

start() {
	log_start $NAME
	$EXEC $ARGS >/dev/null 2>&1
	check_status
}

stop() {
	log_stop $NAME
	if [ ! -r "$PIDFILE" ]; then
		status_fail
		exit 1
	fi
	killall	$NAME 2>/dev/null
	wait_for_pid removed "$PIDFILE"
	check_status
}

restart() {
	stop
	sleep 1
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}" >&2
	exit 1
	;;
esac
