#!/bin/sh
#
# dbus
#

EXEC=$(which dbus-daemon)

[ -x "$EXEC" ] || exit 0

. /etc/init.d/functions

check_root

# Create needed directories.
[ -d /run/dbus ] || mkdir -p /run/dbus
[ -d /var/lock/subsys ] || mkdir -p /var/lock/subsys
[ -d /tmp/dbus ] || mkdir -p /tmp/dbus

start() {
	log_message "Starting system message bus ... "
	dbus-uuidgen --ensure
	dbus-daemon --system
	check_status
	touch /var/lock/subsys/dbus-daemon
}

stop() {
	log_message "Stopping system message bus ... "
	killall dbus-daemon 2> /dev/null
	check_status
	rm -f /var/lock/subsys/dbus-daemon
	rm -f /run/messagebus.pid
}

restart() {
	stop
	sleep 1
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}" >&2
	;;
esac
