#!/bin/sh
#
# wpa_supplicant
#

NAME="wpa_supplicant"
EXEC="$(which $NAME)"
PIDFILE="/run/wpa_supplicant.pid"
CONFFILE="/etc/wpa_supplicant.conf"
LOGFILE="/var/log/wpa_supplicant.log"
WAITDELAY=5

[ -x "$EXEC" ] || exit 0
[ -r "$CONFFILE" ] || exit 0

IFACE="wlan0"
[ -r "/etc/default/$NAME" ] && . "/etc/default/$NAME"
[ -z "$ARGS" ] && ARGS="-Dnl80211 -i$IFACE -c$CONFFILE -f$LOGFILE -P$PIDFILE -B"

. /etc/init.d/functions

wait_for_iface() {
	# In case we have a slow-to-appear interface (e.g. eth-over-USB),
	# and we need to configure it, wait until it appears, but not too
	# long either. WAIT_DELAY is in seconds.
	if [ "WAIT_DELAY" -a ! -e "/sys/class/net/$IFACE" ]; then
		printf "Waiting for interface %s to appear " "$IFACE"
		while [ $WAIT_DELAY -gt 0 ]; do
			if [ -e "/sys/class/net/$IFACE" ]; then
				printf "\n"
				return 0
			fi
			sleep 1
			printf "."
			: $((WAIT_DELAY -= 1))
		done
		printf "timeout!\n"
		exit 1
	fi
}

start() {
	wait_for_iface
	printf "Starting %s ... " "$NAME"
	start-stop-daemon -S -q -p "$PIDFILE" -x "$EXEC" -- $ARGS
	check_status
}

stop() {
	printf "Stopping %s ... " "$NAME"
	if [ ! -r "$PIDFILE" ]; then
		status_fail
		exit 1
	fi
	start-stop-daemon -K -q -p "$PIDFILE"
	wait_for_pid removed "$PIDFILE"
	check_status
}

restart() {
	stop
	sleep 1
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}" >&2
	exit 1
	;;
esac

