#!/bin/sh
#
# wpa_supplicant
#

NAME="wpa_supplicant"
EXEC="$(which $NAME)"
PIDFILE="/run/wpa_supplicant.pid"
CONFFILE="/etc/wpa_supplicant.conf"
IFACE="wlan0"
WAIT_DELAY=5

[ -x "$EXEC" ] || exit 0
[ -r "$CONFFILE" ] || exit 0

[ -r "/etc/default/$NAME" ] && . "/etc/default/$NAME"
[ "x$WPASUPPLICANT_DISABLE" = "xyes" ] && exit 0
[ -z "$ARGS" ] && ARGS="-Dnl80211 -i$IFACE -c$CONFFILE -P$PIDFILE -s -B"

. /usr/share/rcinit/functions

check_root

start() {
	wait_for_iface $IFACE $WAIT_DELAY
	log_start $NAME
	start-stop-daemon -S -q -p "$PIDFILE" -x "$EXEC" -- $ARGS
	check_status
}

stop() {
	log_stop $NAME
	if [ ! -r "$PIDFILE" ]; then
		status_fail
		exit 1
	fi
	start-stop-daemon -K -q -p "$PIDFILE"
	wait_for_pid removed "$PIDFILE"
	check_status
}

restart() {
	stop
	sleep 1
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}" >&2
	exit 1
	;;
esac
