#!/bin/sh
#
# ifupdown
#

IFUP=$(which ifup)
IFDOWN=$(which ifdown)

[ -x "$IFUP" ] || exit 0
[ -x "$IFDOWN" ] || exit 0

. /etc/init.d/functions

check_root

# Debian ifupdown needs the /run/network lock directory
mkdir -p /run/network

start() {
	printf "Starting network ... "
	$IFUP -a > /dev/null 2>&1
	check_status
}

stop() {
	printf "Stopping network ... "
	umount --all --force --types nfs,cifs,nfs4 > /dev/null 2>&1
	$IFDOWN -a > /dev/null 2>&1
	check_status
}

restart() {
	stop
	sleep 1
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}" >&2
	exit 1
esac
