#!/usr/bin/bash
#
# ifupdown
#

IFUP=$(which ifup)
IFDOWN=$(which ifdown)

[ -x "$IFUP" ] || exit 0
[ -x "$IFDOWN" ] || exit 0

. /usr/share/rcinit/functions

check_root

# Debian ifupdown needs the /run/network lock directory
mkdir -p /run/network

start() {
	log_start network
	$IFUP -a >/dev/null 2>&1
	check_status
}

stop() {
	log_stop network
	umount --all --force --types nfs,cifs,nfs4 >/dev/null 2>&1
	$IFDOWN -a >/dev/null 2>&1
	check_status
}

restart() {
	stop
	sleep 1
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}" >&2
	exit 1
esac
