#!/bin/sh
#
# hostapd
#

NAME="hostapd"
EXEC=$(which $NAME)
PIDFILE="/run/hostapd.pid"
CONFFILE="/etc/hostapd.conf"
LOGFILE="/var/log/hostapd.log"
IFACE="wlan0"
WAIT_DELAY=5

[ -r "/etc/default/$NAME" ] && . /etc/default/$NAME
[ -z "$ARGS" ] && ARGS="-B -P $PIDFILE -f $LOGFILE $CONFFILE"

[ -x "$EXEC" ] || exit 0
[ -r "$CONFFILE" ] || exit 0

. /etc/init.d/functions

check_root

start() {
	wait_for_iface $IFACE $WAIT_DELAY
	log_start $NAME
	start-stop-daemon -S -q -p "$PIDFILE" -x "$EXEC" -- $ARGS
	check_status
}

stop() {
	log_stop $NAME
	if [ ! -r "$PIDFILE" ]; then
		status_fail
		exit 1
	fi
	start-stop-daemon -K -q -p "$PIDFILE"
	wait_for_pid removed "$PIDFILE"
	check_status
}

restart() {
	stop
	sleep 1
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}" >&2
	exit 1
	;;
esac
