#!/usr/bin/bash
#
# ifplugd
#

NAME="ifplugd"
IFPLUGD="$(which ifplugd)"
[ -x "$IFPLUGD" ] || exit 0

CFG="/etc/ifplugd/ifplugd.conf"

. /usr/share/rcinit/functions

# not using check_root
if [ `id -u` != "0" ] && [ "$1" = "start" -o "$1" = "stop" ] ; then
	echo "You must be root to start, stop or restart $NAME." >&2
	exit 1
fi

[ -f $CFG ] && . $CFG

VERB="$1"
shift

[ "x$*" != "x" ] && INTERFACES="$*"

[ "x$INTERFACES" = "xauto" ] && INTERFACES="`cat /proc/net/dev | awk '{ print $1 }' | egrep '^(eth|wlan)' | cut -d: -f1`"

case "$VERB" in
  start)
	for IF in $INTERFACES ; do
		log_message "Starting $NAME for $IF ... "
		A="`eval echo \$\{ARGS_${IF}\}`"
		[ -z "$A" ] && A="$ARGS"
		$IFPLUGD -i $IF $A >/dev/null 2>&1
		RET=$?
		if [ $RET -eq 0 -o $RET -eq 2 -o $RET -eq 3 ]; then
			status_ok
		else
			status_fail
		fi
	done
	;;
  stop)
	for IF in $INTERFACES ; do
		log_message "Stopping $NAME for $IF ... "
		$IFPLUGD -k -i $IF >/dev/null 2>&1
		check_status
	done
	;;
  status)
	for IF in $INTERFACES ; do
		$IFPLUGD -c -i $IF
	done
	;;
  suspend)
	for IF in $INTERFACES ; do
		log_message "Suspending $NAME for $IF ... "
		$IFPLUGD -S -i $IF
		check_status
	done
	;;
  resume)
	for IF in $INTERFACES ; do
		log_message "Resuming $NAME for $IF ... "
		$IFPLUGD -R -i $IF
		check_status
	done
	;;
  force-reload|restart)
	$0 stop $INTERFACES
	sleep 3
	$0 start $INTERFACES
	;;
  *)
	echo "Usage: $0 {start|stop|restart|force-reload|status|suspend|resume}" >&2
	exit 1
esac
