#!/bin/sh
#
# dnsmasq
#

NAME="dnsmasq"
EXEC=$(which $NAME)
CONFFILE=/etc/dnsmasq.conf
PIDFILE=/var/run/dnsmasq.pid

[ -x "$EXEC" ] || exit 0
[ -f "$CONFFILE" ] || exit 0

. /etc/init.d/functions

mkdir -p /var/lib/dnsmasq

start() {
	printf "Starting $NAME ... "
	$EXEC > /dev/null 2>&1
	check_status
}

stop() {
	printf "Stopping $NAME ... "
	killall $NAME 2> /dev/null
	check_status
}

restart() {
	stop
	sleep 1
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit 0
