#!/bin/sh
#
# dnsmasq
#

NAME="dnsmasq"
EXEC="$(which $NAME)"
CONFFILE="/etc/$NAME.conf"
LOGDIR="/var/log/$NAME"
LOGFILE="$LOGDIR/$NAME.log"
RUNDIR="/run/$NAME"
PIDFILE="$RUNDIR/$NAME.pid"
USER="dnsmasq"
GROUP="dnsmasq"
ARGS="--pid-file=$PIDFILE --user=$USER --group=$GROUP --log-facility=$LOGFILE"

[ -x "$EXEC" ] || exit 0
[ -r "/etc/default/$NAME" ] && . /etc/default/$NAME
[ -f "$CONFFILE" ] || exit 0
[ "x$DNSMASQ_DISABLE" == "xyes" ] && exit 0

. /etc/init.d/functions

check_root

mkdir -p /var/lib/dnsmasq

start() {
	log_start $NAME
	install -d -o $USER -g $GROUP -m 0755 $RUNDIR
	install -d -o $USER -g root -m 0750 $LOGDIR
	$EXEC $ARGS >/dev/null 2>&1
	check_status
}

stop() {
	log_stop $NAME
	if [ ! -r "$PIDFILE" ]; then
		status_fail
		exit 1
	fi
	killall $NAME 2>/dev/null
	wait_for_pid removed $PIDFILE
	check_status
}

restart() {
	stop
	sleep 1
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}" >&2
	exit 1
esac

exit 0
