#!/bin/sh

NAME="sntp"
EXEC=$(which $NAME)

[ -x "$EXEC" ] || exit 0

# sntp uses all the IPs resolved for the hostname (i.e. pool.ntp.org has 4).
# It will try each until they either all timeout or time has been set. Thus
# default to only providing one NTP pool host.
SNTP_SERVERS="pool.ntp.org"
# Step if time delta is greater then 128ms, otherwise slew
SNTP_ARGS="-Ss -M 128"
SNTP_KEY_CACHE="/tmp/kod"

[ -r "/etc/default/$NAME" ] && . "/etc/default/$NAME"

. /etc/init.d/functions

start() {
	printf 'Starting %s ... ' "$NAME"
	# Create key cache file to prevents warning that file is missing
	touch $SNTP_KEY_CACHE
	# shellcheck disable=SC2086 # we need the word splitting
	$EXEC $SNTP_ARGS -K $SNTP_KEY_CACHE $SNTP_SERVERS
	# sntp behavior
	# - Does not background
	# - Does not infinitely block
	# - Time-out w/o network = ~2 sec
	# - Time-out w/ network = ~5sec * # of servers
	check_status
}

stop() {
	:
}

restart() {
	:
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}" >&2
	exit 1
	;;
esac
