#!/bin/sh
#
# gpsd
#

NAME=gpsd
EXEC=$(which $NAME)
DEVICES="/dev/ttyS1"
PIDFILE=/var/run/$NAME.pid
SOCKFILE=/var/run/$NAME.sock

[ -x "$EXEC" ] || exit 0

. /etc/init.d/functions

start() {
	printf "Starting $NAME ... "
	start-stop-daemon -S -q -p $PIDFILE --exec $EXEC -- -P $PIDFILE $DEVICES -n -F $SOCKFILE
	check_status
}

stop() {
	printf "Stopping $NAME ... "
	start-stop-daemon -K -q -p $PIDFILE
	check_status
	rm -f $PIDFILE
}

restart() {
	stop
	sleep 1
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac
