#!/bin/sh
#
# gpsd
#

NAME=gpsd
EXEC=$(which $NAME)
DEVICE="/dev/ttyS1"
PIDFILE=/run/$NAME.pid
SOCKFILE=/run/$NAME.sock

[ -x "$EXEC" ] || exit 0

[ -r "/etc/default/$NAME" ] && . "/etc/default/$NAME"

. /etc/init.d/functions

start() {
	printf "Starting $NAME ... "
	ln -sf $DEVICE /dev/gps0
	start-stop-daemon -S -q -p $PIDFILE --exec $EXEC -- -P $PIDFILE -n -F $SOCKFILE /dev/gps0
	check_status
}

stop() {
	printf "Stopping $NAME ... "
	start-stop-daemon -K --remove-pidfile -q \
		-p $PIDFILE
	check_status
}

restart() {
	stop
	sleep 1
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac
