#!/bin/sh

NAME="ntpd"
EXEC=$(which $NAME)

[ -x "$EXEC" ] || exit 0

# shellcheck source=/dev/null
[ -r "/etc/default/$NAME" ] && . "/etc/default/$NAME"

. /etc/init.d/functions

start() {
	printf 'Starting %s ... ' "$NAME"
	# Create ntp directory
	mkdir -p /var/lib/ntp
	start-stop-daemon -S -q -x $EXEC -- -g
	check_status
}

stop() {
	printf 'Stopping %s ... ' "$NAME"
	start-stop-daemon -K -q -n $NAME
	check_status
}

restart() {
	stop
	sleep 1
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}" >&2
	exit 1
	;;
esac
