#!/bin/sh

NAME="ntpd"
EXEC=$(which $NAME)
ARGS="-g -l /var/log/ntpd.log -p /run/ntpd.pid"

[ -x "$EXEC" ] || exit 0

# shellcheck source=/dev/null
[ -r "/etc/default/$NAME" ] && . "/etc/default/$NAME"

. /etc/init.d/functions

start() {
	printf 'Starting %s ... ' "$NAME"
	# Create ntp directory
	mkdir -p /var/lib/ntp 2> /dev/null
	$EXEC $ARGS > /dev/null 2>&1
	check_status
}

stop() {
	printf 'Stopping %s ... ' "$NAME"
	killall $NAME 2> /dev/null
	check_status
}

restart() {
	stop
	sleep 1
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}" >&2
	exit 1
	;;
esac
