#!/bin/sh

NAME="ntpd"
EXEC=$(which $NAME)
LOGFILE="/var/log/ntpd.log"
PIDFILE="/run/ntpd.pid"
ARGS="-g -l $LOGFILE -p $PIDFILE"

[ -x "$EXEC" ] || exit 0

[ -r "/etc/default/$NAME" ] && . "/etc/default/$NAME"

. /etc/init.d/functions

check_root

# Create ntp directory
mkdir -p /var/lib/ntp 2> /dev/null

start() {
	printf "Starting %s ... " "$NAME"
	$EXEC $ARGS > /dev/null 2>&1
	check_status
}

stop() {
	printf "Stopping %s ... " "$NAME"
	if [ ! -r "$PIDFILE" ]; then
		status_fail
		exit 1
	fi
	killall $NAME 2> /dev/null
	wait_for_pid removed $PIDFILE
	check_status
}

restart() {
	stop
	sleep 1
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}" >&2
	exit 1
	;;
esac
