#!/bin/sh
#
# mosquitto
#

NAME="mosquitto"
EXEC=$(which $NAME)
ARGS="-c /etc/mosquitto/mosquitto.conf -d"
USER="mosquitto"
GROUP="mosquitto"
RUNDIR="/run/mosquitto"
PIDFILE="$RUNDIR/mosquitto.pid"
LOGDIR="/var/log/mosquitto"

[ -x "$EXEC" ] || exit 0
[ -r "/etc/default/$NAME" ] && . "/etc/default/$NAME"

. /etc/init.d/functions

check_root

start() {
	printf "Starting %s ... " "$NAME"
	install -d -o $USER -g $GROUP -m 0770 $LOGDIR
	install -d -o $USER -g $GROUP -m 0775 $RUNDIR
	start-stop-daemon -S -q -p $PIDFILE -x $EXEC -- $ARGS
	check_status
}

stop() {
	printf "Stopping %s ... " "$NAME"
	if [ ! -r "$PIDFILE" ]; then
		status_fail
		exit 1
	fi
	start-stop-daemon -K -q -p $PIDFILE -u $USER > /dev/null 2>&1
	wait_for_pid removed $PIDFILE
	check_status
}

restart() {
	stop
	sleep 1
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}" >&2
	exit 1
esac

exit $?
