#!/bin/sh
#
# mariadb
#

NAME="mysql"
MYSQL_LIB="/var/lib/mysql"
MYSQL_RUN="/run/mysql"
MYSQL_PIDFILE="$MYSQL_RUN/mysqld.pid"
MYSQL_LOG="/var/log/mysql"
MYSQL_LOGFILE="$MYSQL_LOG/mysqld.log"
MYSQL_BIN="/usr/bin"
MYSQL_USER="mysql"
MYSQL_PREFIX="/usr"
WAIT_DELAY=10

[ -x "$MYSQL_BIN/mysqld_safe" ] || exit 0
[ -r "/etc/default/$NAME" ] && . "/etc/default/$NAME"
[ "x$MYSQLD_DISABLE" = "xyes" ] && exit 0

. /etc/init.d/functions

check_root

wait_for_ready() {
	while [ $WAIT_DELAY -gt 0 ]; do
		if "$MYSQL_BIN/mysqladmin" ping >/dev/null 2>&1; then
			return 0
		fi
		sleep 1
		: $((WAIT_DELAY -= 1))
	done
	return 1
}

start() {
	if [ "`ls -1 $MYSQL_LIB 2> /dev/null | wc -l`" = "0" ]; then
		log_message "Creating $NAME system tables ... "
		$MYSQL_BIN/mysql_install_db --basedir=$MYSQL_PREFIX \
			--user=$MYSQL_USER --datadir=$MYSQL_LIB >/dev/null 2>&1
		if [ $? -ne 0 ]; then
			status_fail
			exit 1
		fi
		status_ok
	fi

	# mysqld runs as user mysql, but /run is only writable by root
	# so create a subdirectory for mysql.
	install -d -o mysql -g root -m 0755 $MYSQL_RUN

	# Also create logging directory as user mysql.
	install -d -o mysql -g root -m 0755 $MYSQL_LOG

	# We don't use start-stop-daemon because mysqld has its own
	# wrapper script.
	log_start $NAME
	$MYSQL_BIN/mysqld_safe --pid-file=$MYSQL_PIDFILE --user=$MYSQL_USER \
		--log-error=$MYSQL_LOGFILE >/dev/null 2>&1 &
	wait_for_ready
	check_status
}

stop() {
	log_stop $NAME
	if [ ! -r "$MYSQL_PIDFILE" ]; then
		status_fail
		exit 1
	fi
	kill `cat $MYSQL_PIDFILE` >/dev/null 2>&1
	wait_for_pid removed $MYSQL_PIDFILE
	check_status
}

restart() {
	stop
	sleep 1
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}" >&2
	;;
esac
