#!/bin/sh

NAME="php-fpm"
php_fpm_BIN=$(which $NAME)
php_fpm_CONF="/etc/php-fpm.conf"
php_fpm_PID="/run/php-fpm.pid"

php_opts="--fpm-config $php_fpm_CONF --pid $php_fpm_PID"

[ -x "$php_fpm_BIN" ] || exit 0

. /etc/init.d/functions

check_root

start() {
	log_start $NAME
	$php_fpm_BIN --daemonize $php_opts
	RET=$?
	if [ "$RET" != 0 ] ; then
		status_fail
		exit 1
	fi
	wait_for_pid created $php_fpm_PID
	check_status
}

stop() {
	log_stop $NAME
	if [ ! -r $php_fpm_PID ] ; then
		status_fail
		exit 1
	fi
	kill -QUIT `cat $php_fpm_PID`
	wait_for_pid removed $php_fpm_PID
	check_status
}

status() {
	if [ ! -r $php_fpm_PID ] ; then
		log_message "$NAME is stopped\n"
		exit 0
	fi
	PID=`cat $php_fpm_PID`
	if ps -p $PID | grep -q $PID; then
		log_message "$NAME (pid $PID) is running\n"
	else
		log_message "$NAME dead but pid file exists\n"
	fi
}

forcequit() {
	log_message "Terminating $NAME ... "
	if [ ! -r $php_fpm_PID ] ; then
		status_fail
		exit 1
	fi
	kill -TERM `cat $php_fpm_PID`
	wait_for_pid removed $php_fpm_PID
	check_status
}

restart() {
	stop
	sleep 1
	start
}

reload() {
	log_message "Reloading $NAME ... "
	if [ ! -r $php_fpm_PID ] ; then
		status_fail
		exit 1
	fi
	kill -USR2 `cat $php_fpm_PID`
	check_status
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  status)
	status
	;;
  force-quit)
	forcequit
	;;
  restart)
	restart
	;;
  reload)
	reload
	;;
  *)
	echo "Usage: $0 {start|stop|force-quit|restart|reload|status}" >&2
	exit 1
	;;
esac
