#!/bin/sh

DAEMON="proftpd"
EXEC=$(which $DAEMON)

test -x "$EXEC" || exit 0

. /etc/init.d/functions

start() {
	printf 'Starting %s ... ' "$DAEMON"
	$EXEC > /dev/null 2>&1
	check_status
}

stop() {
	printf 'Stopping %s ... ' "$DAEMON"
	killall $DAEMON 2> /dev/null
	check_status
}

restart() {
	stop
	sleep 1
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}" >&2
	exit 1
	;;
esac
