#! /bin/sh

NAME="php-fpm"
php_fpm_BIN=$(which $NAME)
php_fpm_CONF=/etc/php-fpm.conf
php_fpm_PID=/var/run/php-fpm.pid

php_opts="--fpm-config $php_fpm_CONF --pid $php_fpm_PID"

[ -x "$php_fpm_BIN" ] || exit 0

. /etc/init.d/functions

wait_for_pid() {
	try=0

	while test $try -lt 35 ; do
		case "$1" in
			'created')
			if [ -f "$2" ] ; then
				try=''
				break
			fi
			;;

			'removed')
			if [ ! -f "$2" ] ; then
				try=''
				break
			fi
			;;
		esac

		try=`expr $try + 1`
		sleep 1

	done
}

start() {
	printf "Starting $NAME ... "

	$php_fpm_BIN --daemonize $php_opts
	RET=$?
	if [ "$RET" != 0 ] ; then
		status_fail
		exit 1
	fi

	wait_for_pid created $php_fpm_PID

	if [ -n "$try" ] ; then
		status_fail
		exit 1
	else
		status_ok
	fi
}

stop() {
	printf "Stopping $NAME ... "

	if [ ! -r $php_fpm_PID ] ; then
		status_fail
		exit 1
	fi

	kill -QUIT `cat $php_fpm_PID`

	wait_for_pid removed $php_fpm_PID

	if [ -n "$try" ] ; then
		status_fail
		exit 1
	else
		status_ok
	fi
}

status() {
	if [ ! -r $php_fpm_PID ] ; then
		echo "php-fpm is stopped"
		exit 0
	fi

	PID=`cat $php_fpm_PID`
	if ps -p $PID | grep -q $PID; then
		echo "php-fpm (pid $PID) is running..."
	else
		echo "php-fpm dead but pid file exists"
	fi
}

forcequit() {
	printf "Terminating $NAME ... "

	if [ ! -r $php_fpm_PID ] ; then
		status_fail
		exit 1
	fi

	kill -TERM `cat $php_fpm_PID`

	wait_for_pid removed $php_fpm_PID

	if [ -n "$try" ] ; then
		status_fail
		exit 1
	else
		status_ok
	fi
}

restart() {
	stop
	sleep 1
	start
}

reload() {
	printf "Reload service $NAME ... "

	if [ ! -r $php_fpm_PID ] ; then
		status_fail
		exit 1
	fi

	kill -USR2 `cat $php_fpm_PID`
	check_status
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  status)
	status
	;;
  force-quit)
	forcequit
	;;
  restart)
	restart
	;;
  reload)
	reload
	;;
  *)
	echo "Usage: $0 {start|stop|force-quit|restart|reload|status}"
	exit 1
	;;
esac
