#!/bin/sh

NAME="proftpd"
EXEC="$(which $NAME)"
PIDFILE="/var/proftpd/proftpd.pid"

[ -x "$EXEC" ] || exit 0

. /etc/init.d/functions

start() {
	printf "Starting %s ... " "$NAME"
	$EXEC > /dev/null 2>&1
	check_status
}

stop() {
	printf "Stopping %s ... " "$NAME"
	killall $NAME 2> /dev/null
	wait_for_pid removed "$PIDFILE"
	check_status
}

restart() {
	stop
	sleep 1
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}" >&2
	exit 1
	;;
esac
