#!/bin/sh
#
# redis
#

NAME="redis"
EXEC=$(which $NAME-server)
CONF="/etc/$NAME.conf"
DBDIR="/var/lib/$NAME"
RUNDIR="/run/$NAME"
PIDFILE="$RUNDIR/$NAME.pid"
LOGDIR="/var/log/$NAME"
USER="redis"
GROUP="redis"

[ -x "$EXEC" ] || exit 0
[ -f "$CONF" ] || exit 0
[ -d "$DBDIR" ] || exit 0

. /usr/share/rcinit/functions

check_root

start() {
	log_start $NAME
	install -d -o $USER -g $GROUP -m 0770 $LOGDIR
	install -d -o $USER -g $GROUP -m 0775 $RUNDIR
	ulimit -n 10240
	start-stop-daemon -S -q -b -c $USER:$GROUP \
		-d $DBDIR --umask 0007 --pidfile $PIDFILE \
		--exec $EXEC -- $CONF
	check_status
}

stop() {
	log_stop $NAME
	if [ ! -r "$PIDFILE" ]; then
		status_fail
		exit 1
	fi
	/usr/bin/redis-cli shutdown >/dev/null 2>&1
	wait_for_pid removed $PIDFILE
	check_status
}

restart() {
	stop
	sleep 1
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}" >&2
	exit 1
esac
