#!/bin/sh
#
# redis
#

NAME="redis"
EXEC=$(which $NAME-server)
CONF="/etc/redis.conf"

[ -x "$EXEC" ] || exit 0
[ -f "$CONF" ] || exit 0

. /etc/init.d/functions

start() {
	printf "Starting $NAME ... "
	install -d -o redis -g redis -m 0777 /var/run/redis
	touch /var/log/redis.log
	chown redis:redis /var/log/redis.log
	ulimit -n 10240
	umask 077
	start-stop-daemon -S -q -c redis:redis -b \
		--exec $EXEC -- $CONF
	check_status
}

stop() {
	printf "Stopping $NAME ... "
	/usr/bin/redis-cli shutdown > /dev/null 2>&1
	check_status
}

restart() {
	stop
	sleep 2
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac
