#!/bin/sh
#
# ssh
#

NAME="sshd"
KEYGEN_BIN="$(which ssh-keygen)"
KEYGEN_ARGS="-A"
SSHD_BIN="$(which sshd)"
SSHD_ARGS=""
PIDFILE="/run/sshd.pid"
ETC_DIR="/etc/ssh"
KEY_FILES="ssh_host_dsa_key.pub ssh_host_ed25519_key ssh_host_rsa_key.pub ssh_host_ecdsa_key ssh_host_ed25519_key.pub ssh_host_dsa_key ssh_host_ecdsa_key.pub ssh_host_rsa_key"

[ -x "$KEYGEN_BIN" ] || exit 0
[ -x "$SSHD_BIN" ] || exit 0

. /etc/init.d/functions

check_root

umask 0002

start() {
	# Check for missing keys
	KEYGEN="no"
	for i in $KEY_FILES; do
		[ ! -f "$ETC_DIR/$i" ] && KEYGEN="yes"
	done

	# Create any missing keys
	if [ "$KEYGEN" = "yes" ]; then
		log_message "Creating ssh keys ... "
		$KEYGEN_BIN $KEYGEN_ARGS > /dev/null 2>&1
		check_status
	fi

	log_start $NAME
	$SSHD_BIN $SSHD_ARGS > /dev/null 2>&1
	check_status
}

stop() {
	log_stop $NAME
	if [ ! -r "$PIDFILE" ]; then
		status_fail
		exit 1
	fi
	killall $NAME 2> /dev/null
	wait_for_pid removed $PIDFILE
	check_status
}

restart() {
	log_message "Restarting $NAME ... "
	PID="`cat $PIDFILE 2> /dev/null`"
	if [ -n "$PID" ]; then
		kill $PID
	else
		status_fail
		exit 1
	fi
	sleep 1
	$SSHD_BIN $SSHD_ARGS > /dev/null 2>&1
	check_status
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}" >&2
	exit 1
esac
