#!/bin/sh
#
# lighttpd
#

NAME="lighttpd"
EXEC="$(which $NAME)"
RUNDIR="/run/lighttpd"
PIDFILE="$RUNDIR/$NAME.pid"
LOGDIR="/var/log/lighttpd"
ERRORLOG="$LOGDIR/error.log"
ACCESSLOG="$LOGDIR/access.log"
USER="www-data"
GROUP="www-data"
CONFFILE="/etc/$NAME/$NAME.conf"
ARGS="-f $CONFFILE"

[ -x "$EXEC" ] || exit 0
[ -r "/etc/default/$NAME" ] && . "/etc/default/$NAME"

. /usr/share/rcinit/functions

start() {
	log_start $NAME
	install -d -o $USER -g $GROUP -m 0775 $RUNDIR
	install -d -o $USER -g $GROUP -m 0770 $LOGDIR
	start-stop-daemon -S -q -p $PIDFILE --exec $EXEC -- $ARGS
	check_status
}

stop() {
	log_stop $NAME
	if [ ! -r "$PIDFILE" ]; then
		status_fail
		exit 1
	fi
	start-stop-daemon -K -q -p $PIDFILE
	wait_for_pid removed $PIDFILE
	check_status
}

restart() {
	stop
	sleep 1
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}" >&2
	exit 1
esac

exit $?
