#!/bin/sh

EXEC="openvpn"
DAEMON="$(which $EXEC)"
CONFIG_DIR="/etc/openvpn"
DEFAULT_FILE="/etc/default/openvpn"

[ -x "$DAEMON" ] || exit 0
[ -d "$CONFIG_DIR" ] || exit 0
[ -f "$DEFAULT_FILE" ] && . $DEFAULT_FILE
[ "x$OPENVPN_DISABLE" = "xyes" ] && exit 0

. /usr/share/rcinit/functions

check_root

start_vpn () {
	log_message "Starting $EXEC $NAME ... "
	start-stop-daemon -S -p /run/openvpn.$NAME.pid -x $DAEMON -- \
		--daemon --writepid /run/openvpn.$NAME.pid               \
		--config $CONFIG_DIR/$NAME.conf --cd $CONFIG_DIR         \
		>/dev/null 2>&1
	check_status
}

stop_vpn () {
	log_message "Stopping $EXEC $NAME ... "
	start-stop-daemon -K -p /run/openvpn.$NAME.pid -x $DAEMON    \
		>/dev/null 2>&1
	check_status
}

case "$1" in
start)
	if test -z $2 ; then
		for CONFIG in `cd $CONFIG_DIR; ls *.conf 2>/dev/null`; do
			NAME=${CONFIG%%.conf}
			start_vpn
		done
	else
		if test -e $CONFIG_DIR/$2.conf ; then
			NAME=$2
			start_vpn
		else
			log_message "No such VPN: $2\n"
		fi
	fi
	;;
stop)
	if test -z $2 ; then
		for PIDFILE in `ls /run/openvpn.*.pid 2>/dev/null`; do
			NAME=`echo $PIDFILE | cut -c14-`
			NAME=${NAME%%.pid}
			stop_vpn
		done
	else
		if test -e /run/openvpn.$2.pid ; then
			PIDFILE=`ls /run/openvpn.$2.pid 2>/dev/null`
			NAME=`echo $PIDFILE | cut -c14-`
			NAME=${NAME%%.pid}
			stop_vpn
		else
			log_message "No such VPN: $2\n"
		fi
	fi
	;;
# We only 'reload' for running VPNs. New ones will only start with 'start' or 'restart'.
reload|force-reload)
	for PIDFILE in `ls /run/openvpn.*.pid 2>/dev/null`; do
		NAME=`echo $PIDFILE | cut -c18-`
		NAME=${NAME%%.pid}
		# If openvpn if running under a different user than root we'll need to restart
		if egrep '^( |\t)*user' $CONFIG_DIR/$NAME.conf >/dev/null 2>&1 ; then
			stop_vpn
			sleep 1
			start_vpn
		else
			log_message "Reloading $DAEMON $NAME ... "
			kill -HUP `cat $PIDFILE` || true
			check_status
		fi
	done
	;;
restart)
	$0 stop $2
	sleep 3
	$0 start $2
	;;
*)
	echo "Usage: $0 {start|stop|reload|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0
