#!/usr/bin/bash
#
# bluetoothd
#

NAME="bluetoothd"
EXEC="/usr/libexec/bluetooth/$NAME"
ARGS="--experimental"
PID_FILE="/run/$NAME.pid"

[ -x "$EXEC" ] || exit 0

. /usr/share/rcinit/functions

check_root

start() {
	log_message "Starting $NAME ... "
	start-stop-daemon -b -S -q -m -p $PID_FILE --exec $EXEC -- $ARGS
	check_status
}

stop() {
	log_message "Stopping $NAME ... "
	start-stop-daemon -K -q -p $PID_FILE
	check_status
}

restart() {
	stop
	sleep 1
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}" >&2
	exit 1
esac
