#!/bin/sh
#
# bluetoothd
#

NAME="bluetoothd"
EXEC="/usr/libexec/bluetooth/$NAME"
ARGS="--experimental"
PID_FILE="/var/run/$NAME.pid"

[ -x "$EXEC" ] || exit 0

. /etc/init.d/functions

check_root

start() {
	printf "Starting %s ... " "$NAME"
	start-stop-daemon -b -S -q -m -p $PID_FILE --exec $EXEC -- $ARGS
	check_status
}

stop() {
	printf "Stopping %s ... " "$NAME"
	start-stop-daemon -K -q -p $PID_FILE
	check_status
}

restart() {
	stop
	sleep 1
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}" >&2
	exit 1
esac
