#!/bin/sh
#
# inadyn
#

NAME="inadyn"
EXEC=$(which $NAME)
CACHEDIR="/var/lib/inadyn"
ARGS="--cache-dir=$CACHEDIR"
CONF="/etc/inadyn.conf"
PIDFILE="/run/inadyn.pid"

[ -f $CONF ] || exit 0
[ -x $EXEC ] || exit 0

. /etc/init.d/functions

check_root

start() {
	printf "Starting %s ... " "$NAME"
	mkdir -p $CACHEDIR
	start-stop-daemon -b -q -S -p $PIDFILE -x $EXEC -- $ARGS
	check_status
}

stop() {
	printf "Stopping %s ... " "$NAME"
	if [ ! -r "$PIDFILE" ] ; then
		status_fail
		exit 1
	fi
	start-stop-daemon -q -K -p $PIDFILE -x $EXEC
	wait_for_pid removed $PIDFILE
	check_status
}

restart() {
	stop
	sleep 1
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}" >&2
	exit 1
esac
