#!/bin/sh
#
# inadyn
#

. /etc/init.d/functions

NAME="inadyn"
EXEC=$(which $NAME)
CACHEDIR="/var/lib/inadyn"
ARGS="--cache-dir=$CACHEDIR"
CONF="/etc/inadyn.conf"
PIDFILE="/run/inadyn.pid"

[ -f $CONF ] || exit 0
[ -x $EXEC ] || exit 0

start() {
	printf "Starting $NAME ... "
	mkdir -p $CACHEDIR
	start-stop-daemon -b -q -S -p $PIDFILE -x $EXEC -- $ARGS
	check_status
}

stop() {
	printf "Stopping $NAME ... "
	start-stop-daemon -q -K -p $PIDFILE -x $EXEC
	check_status
}

restart() {
	stop
	sleep 1
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac
