#!/usr/bin/bash
#
# nmbd
#

NAME="nmbd"
EXEC=$(which $NAME)
ARGS="-D"
CONF="/etc/samba/smb.conf"
CACHEDIR="/var/cache/samba"
LOGDIR="/var/log/samba"
LOCKDIR="/run/lock/subsys"
RUNDIR="/run/samba"
PIDFILE="$RUNDIR/nmbd.pid"

[ -x "$EXEC" ] || exit 0
[ -f "$CONF" ] || exit 0

. /etc/init.d/functions

check_root

start() {
	log_start $NAME
	install -d -m 0755 $CACHEDIR
	install -d -m 0750 $LOGDIR
	install -d -m 0775 $LOCKDIR
	install -d -m 0775 $RUNDIR
	$EXEC $ARGS >/dev/null 2>&1
	check_status
}

stop() {
	log_stop $NAME
	kill -9 `pidof $NAME` >/dev/null 2>&1
	check_status
	rm -f "$PIDFILE"
}

restart() {
	stop
	sleep 1
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}" >&2
	exit 1
esac

exit 0
