#!/usr/bin/bash
#
# smbd
#

NAME="smbd"
EXEC=$(which $NAME)
ARGS="-D"
CONF="/etc/samba/smb.conf"
CACHEDIR="/var/cache/samba"
LOGDIR="/var/log/samba"
LOCKDIR="/run/lock/subsys"
RUNDIR="/run/samba"
PIDFILE="$RUNDIR/smbd.pid"

. /etc/init.d/functions

[ -x "$EXEC" ] || exit 0
[ -f "$CONF" ] || exit 0

start() {
	log_start $NAME
	install -d -m 0755 $CACHEDIR
	install -d -m 0750 $LOGDIR
	install -d -m 0775 $LOCKDIR
	install -d -m 0775 $RUNDIR
	$EXEC $ARGS >/dev/null 2>&1
	check_status
	touch "$LOCKDIR/smb"
}

stop() {
	log_stop $NAME
	kill -9 `pidof $NAME` >/dev/null 2>&1
	check_status
	rm -f "$PIDFILE"
	rm -f "$LOCKDIR/smb"
}

restart() {
	stop
	sleep 1
	start
}

reload() {
	log_message "Reloading $NAME ... "
	kill -HUP `pidof smbd` >/dev/null 2>&1
	check_status
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart)
	restart
	;;
  reload)
	reload
	;;
  *)
	echo "Usage: $0 {start|stop|restart|reload}" >&2
	exit 1
esac

exit 0
