#!/bin/sh
#
# cupsd
#

NAME="cupsd"
EXEC="$(which $NAME)"
ARGS=""

[ -x "$EXEC" ] || exit 0

. /etc/init.d/functions

check_root

start() {
	printf "Starting %s ... " "$NAME"
	$EXEC $ARGS > /dev/null 2>&1
	check_status
}

stop() {
	printf "Stopping %s ... " "$NAME"
	killall $NAME 2> /dev/null
	check_status
}

restart() {
	stop
	sleep 1
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}" >&2
	exit 1
esac

exit 0
