#!/bin/sh
#
# cupsd
#

CUPS_BIN="/usr/sbin/cupsd"
CUPS_ARGS=""

[ -x "$CUPS_BIN" ] || exit 0

. /etc/init.d/functions

start() {
	printf "Starting cupsd ... "
	$CUPS_BIN $CUPS_ARGS
	check_status
}

stop() {
	printf "Stopping cupsd ... "
	killall cupsd 2> /dev/null
	check_status
}

restart() {
	stop
	sleep 1
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}" >&2
	exit 1
esac

exit 0
