#!/bin/sh
#
# crond
#

NAME="crond"
EXEC=$(which $NAME)
SPOOLDIR="/var/spool/cron/crontabs"
PIDFILE="/run/crond.pid"

[ -x "$EXEC" ] || exit 0

. /etc/init.d/functions

start() {
	printf "Starting $NAME ... "
	mkdir -p $SPOOLDIR
	$EXEC > /dev/null 2>&1
	check_status
}

stop() {
	printf "Stopping $NAME ... "
	if [ ! -r "$PIDFILE" ] ; then
		status_fail
		exit 1
	fi
	killall $NAME 2> /dev/null
	wait_for_pid removed $PIDFILE
	check_status
}

restart() {
	stop
	sleep 1
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac
