#!/usr/bin/bash
#
# crond
#

NAME="crond"
EXEC=$(which $NAME)
SPOOLDIR="/var/spool/cron/crontabs"
PIDFILE="/run/crond.pid"

[ -x "$EXEC" ] || exit 0

. /usr/share/rcinit/functions

check_root

start() {
	log_start $NAME
	install -d -m 0700 $SPOOLDIR
	$EXEC >/dev/null 2>&1
	check_status
}

stop() {
	log_stop $NAME
	if [ ! -r "$PIDFILE" ] ; then
		status_fail
		exit 1
	fi
	killall $NAME 2>/dev/null
	check_status
	# crond does not remove pid file
	rm -f "$PIDFILE"
}

restart() {
	stop
	sleep 1
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}" >&2
	exit 1
esac
