#!/usr/bin/bash
#
# vnstatd
#

NAME="vnstatd"
EXEC=$(which $NAME)
ARGS="--daemon"
VARDIR="/var/lib/vnstat"
PIDFILE="/run/vnstat/vnstat.pid"

[ -x "$EXEC" ] || exit 1
[ -r "/etc/default/$NAME" ] && . "/etc/default/$NAME"
[ "x$VNSTATD_DISABLE" = "xyes" ] && exit 0

. /etc/init.d/functions

check_root

start() {
	log_start $NAME
	install -d -m 0755 $VARDIR
	start-stop-daemon -S -q -p $PIDFILE -x $EXEC -- $ARGS >/dev/null 2>&1
	check_status
}

stop() {
	log_stop $NAME
	if [ ! -r "$PIDFILE" ] ; then
		status_fail
		exit 1
	fi
	start-stop-daemon -K -q -p $PIDFILE -n $NAME
	wait_for_pid removed $PIDFILE
	check_status
}

restart() {
	stop
	sleep 1
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}" >&2
	exit 1
esac
