#!/bin/sh
#
# transmission-daemon
#

NAME="transmission-daemon"
EXEC="$(which $NAME)"
PIDDIR="/run/transmission"
PIDFILE="$PIDDIR/transmission-daemon.pid"
CONFDIR="/var/lib/transmission/info"
LOGDIR="/var/log/transmission"
LOGFILE="$LOGDIR/transmission.log"
USER="transmission"
DEFAULT_FILE="/etc/default/transmission"
ARGS="-f --pid-file $PIDFILE --config-dir $CONFDIR --logfile $LOGFILE"

[ -x "$EXEC" ] || exit 0
[ -f "$DEFAULT_FILE" ] && . $DEFAULT_FILE
[ "x$TRANSMISSION_DISABLE" = "xyes" ] && exit 0

. /etc/init.d/functions

start() {
	printf "Starting %s ... " "$NAME"
	if [ ! -f "$CONFDIR/settings.json" ]; then
		status_fail
		exit 1
	fi
	install -d -o $USER -g $USER -m 0770 $LOGDIR
	install -d -o $USER -g $USER -m 0775 $PIDDIR
	start-stop-daemon -S -c $USER -x $EXEC -p $PIDFILE -b -- $ARGS > /dev/null 2>&1
	check_status
}

stop() {
	printf "Stopping %s ... " "$NAME"
	if [ ! -r $PIDFILE ] ; then
		status_fail
		exit 1
	fi
	killall $NAME 2> /dev/null
	wait_for_pid removed $PIDFILE
	check_status
}

restart() {
	stop
	sleep 1
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit 0
