#!/bin/sh
#
# fail2ban
#

NAME="fail2ban"
EXEC=$(which $NAME-server)
VARDIR="/var/run/fail2ban"
PIDFILE="/run/fail2ban/fail2ban.pid"
ARGS="-xf start"

[ -x "$EXEC" ] || exit 0

. /etc/init.d/functions

start() {
	printf "Starting %s ... " "$NAME"
	mkdir -p $VARDIR
	start-stop-daemon -S -q -b -m -p $PIDFILE -x $EXEC -- $ARGS
	check_status
}

stop() {
	printf "Stopping %s ... " "$NAME"
	if [ ! -r "$PIDFILE" ]; then
		status_fail
		exit 1
	fi
	start-stop-daemon -K -q -p $PIDFILE
	wait_for_pid removed $PIDFILE
	check_status
}

restart() {
	stop
	sleep 1
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
	;;
esac
