#!/bin/sh
#
# mpd
#

NAME="mpd"
EXEC=$(which $NAME)
CONF="/etc/mpd.conf"
RUNDIR="/run/mpd"
PIDFILE="$RUNDIR/mpd.pid"

[ -x "$EXEC" ] || exit 0
[ -f "$CONF" ] || exit 0

. /etc/init.d/functions

check_root

start() {
	printf "Starting $NAME ... "
	install -d -m 0775 $RUNDIR
	start-stop-daemon --start --quiet --background --exec $EXEC
	check_status
}

stop() {
	printf "Stopping $NAME ... "
	if [ ! -r "$PIDFILE" ]; then
		status_fail
		exit 1
	fi
	start-stop-daemon --stop --quiet --pidfile $PIDFILE
	wait_for_pid removed $PIDFILE
	check_status
}

restart() {
	stop
	sleep 1
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}" >&2
	exit 1
esac
