#!/bin/sh
#
# mpd
#

NAME="mpd"
EXEC=$(which $NAME)
CONF="/etc/mpd.conf"
PIDFILE="/var/run/mpd/mpd.pid"

[ -x "$EXEC" ] || exit 0
[ -f "$CONF" ] || exit 0

./etc/init.d/functions

start() {
	printf "Starting $NAME ... "
	start-stop-daemon --start --quiet --background --exec $EXEC
	check_status
}

stop() {
	printf "Stopping $NAME ... "
	start-stop-daemon --stop --quiet --pidfile $PIDFILE
	check_status
}

restart() {
	stop
	sleep 1
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac
