#!/bin/bash

. /etc/init.d/functions

check_root

BACKEND_MODULES="xen-evtchn xen-gntdev xen-gntalloc xen-blkback xen-netback xen-pciback evtchn gntdev netbk blkbk xen-scsibk usbbk pciback xen-acpi-processor blktap2"

. /etc/xen/scripts/hotplugpath.sh

xencommons_config=/etc/sysconfig

test -f $xencommons_config/xencommons && . $xencommons_config/xencommons

XENCONSOLED_PIDFILE=/var/run/xen/xenconsoled.pid
QEMU_PIDFILE=/var/run/xen/qemu-dom0.pid
shopt -s extglob

# not running in Xen dom0 or domU
if ! test -d /proc/xen ; then
	exit 0
fi

# mount xenfs in dom0 or domU with a pv_ops kernel
if test "x$1" = "xstart" && \
   ! test -f /proc/xen/capabilities && \
   ! grep '^xenfs ' /proc/mounts >/dev/null;
then
	mount -t xenfs xenfs /proc/xen
fi

# run this script only in dom0:
# no capabilities file in xenlinux domU kernel
# empty capabilities file in pv_ops domU kernel
if test -f /proc/xen/capabilities && \
   ! grep -q "control_d" /proc/xen/capabilities ; then
	exit 0
fi

do_start () {
	local mod

	for mod in $BACKEND_MODULES ; do modprobe "$mod" &>/dev/null ; done

	mkdir -m700 -p ${XEN_RUN_DIR}
	mkdir -m700 -p ${XEN_LOCK_DIR}
	mkdir -p ${XEN_LOG_DIR}
	mkdir -p /var/lib/xen

	printf "Starting xenstore ... "
	/etc/xen/scripts/launch-xenstore > /dev/null 2>&1
	if [ "$?" = "0" ]; then
		status_ok
	else
		status_fail
		exit 1
	fi

	printf "Setting domain 0 name, domid and json config ... "
	${LIBEXEC_BIN}/xen-init-dom0 ${XEN_DOM0_UUID} > /dev/null 2>&1
	check_status

	printf "Starting xenconsoled ... "
	test -z "$XENCONSOLED_TRACE" || XENCONSOLED_ARGS=" --log=$XENCONSOLED_TRACE"
	${sbindir}/xenconsoled --pid-file=$XENCONSOLED_PIDFILE $XENCONSOLED_ARGS > /dev/null 2>&1
	check_status

	printf "Starting qemu as disk backend for dom0 ... "
	test -z "$QEMU_XEN" && QEMU_XEN="/usr/lib/xen/bin/qemu-system-i386"
	$QEMU_XEN -xen-domid 0 -xen-attach -name dom0 -nographic -M xenpv -daemonize \
		-monitor /dev/null -serial /dev/null -parallel /dev/null \
		-pidfile $QEMU_PIDFILE > /dev/null 2>&1
	check_status
}

do_stop () {
	printf "Stopping xenconsoled ... "
	if read 2>/dev/null <$XENCONSOLED_PIDFILE pid; then
		kill $pid
		while kill -9 $pid >/dev/null 2>&1; do sleep 1; done
		rm -f $XENCONSOLED_PIDFILE
		status_ok
	else
		status_fail
	fi

	printf "Stopping qemu ... "
	if read 2>/dev/null <$QEMU_PIDFILE pid; then
		kill $pid
		while kill -9 $pid >/dev/null 2>&1; do sleep 1; done
		rm -f $QEMU_PIDFILE
		status_ok
	else
		status_fail
	fi

	printf "Stopping xenstored ... "
	killall xenstored 2> /dev/null
	check_status
}

case "$1" in
  start)
	do_start
	;;
  status)
	test -f /var/run/xen/xenstored.pid
	;;
  stop)
	do_stop
	;;
  reload)
	echo >&2 'Reload not available; use force-reload'; exit 1
	;;
  force-reload|restart)
	do_stop
	do_start
	;;
  *)
	# do not advertise unreasonable commands that there is no reason
	# to use with this device
	echo "Usage: $0 {start|stop|status|restart|force-reload}" >&2
	exit 1
esac

exit $?
