#!/bin/sh
#
# autossh
#

NAME="autossh"
EXEC=$(which $NAME)

[ -x "$EXEC" ] || exit 0

. /etc/init.d/functions

check_root

start() {
	:
}

stop() {
	printf "Stopping $NAME ... "
	killall $NAME 2> /dev/null
	status_ok
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  *)
	echo "Usage: $0 {start|stop}"
	exit 1
esac
