#!/bin/sh
#
# autossh
#

NAME="autossh"
EXEC=$(which $NAME)

[ -x "$EXEC" ] || exit 0

. /usr/share/rcinit/functions

check_root

start() {
	:
}

stop() {
	log_stop $NAME
	killall $NAME 2>/dev/null
	status_ok
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  *)
	echo "Usage: $0 {start|stop}"
	exit 1
esac
