#!/bin/sh
#
# motion
#

NAME="motion"
EXEC=$(which $NAME)
PIDFILE="/run/motion.pid"
CONF="/etc/motion/motion.conf"
ARGS="-c $CONF"

[ -x "$EXEC" ] || exit 0

. /etc/init.d/functions

start() {
	printf "Starting %s ... " "$NAME"
	$EXEC $ARGS > /dev/null 2>&1
	check_status
}

stop() {
	printf "Stopping %s ... " "$NAME"
	if [ ! -r "$PIDFILE" ]; then
		status_fail
		exit 1
	fi
	killall	$NAME 2> /dev/null
	wait_for_pid removed $PIDFILE
	check_status
}

restart() {
	stop
	sleep 1
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}" >&2
	exit 1
	;;
esac
