#!/bin/sh
#
# rpi-psu
#

NAME=rpi-psu
EXEC=$(which $NAME)

[ -x "$EXEC" ] || exit 0

. /usr/share/rcinit/functions

check_root

start() {
	log_start $NAME
	start-stop-daemon -S -q -x $EXEC -b --
	check_status
}

stop() {
	log_stop $NAME
	start-stop-daemon -K -q -n $NAME
	check_status
}

restart() {
	stop
	sleep 1
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart|reload}" >&2
	exit 1
	;;
esac

exit 0
