#!/bin/sh
#
# unifi
#

NAME="unifi"
EXEC="$(which jsvc)"
PIDFILE="/run/unifi/unifi.pid"

[ -x "$EXEC" ] || exit 0

. /usr/share/rcinit/functions

export JAVA_HOME=/opt/java

wait_for_stop()
{
	WAIT_DELAY=30
	while [ $WAIT_DELAY -gt 0 ]; do
		COUNT="$(pgrep -c -f unifi)"
		if [ "$COUNT" -le 1 ]; then
			return 0
		fi
		sleep 1
		: $((WAIT_DELAY -= 1))
	done
	return 1
}

start() {
	log_start "$NAME"
	install -d -o unifi -g unifi -m 0755 /var/lib/unifi
	install -d -o unifi -g unifi -m 0755 /var/log/unifi
	install -d -o unifi -g unifi -m 0755 /run/unifi
	$EXEC \
		-cwd /usr/lib/unifi \
		-home /opt/java \
		-cp /opt/commons-daemon/commons-daemon.jar:/usr/lib/unifi/lib/ace.jar \
		-pidfile $PIDFILE \
		-procname unifi \
		-outfile SYSLOG \
		-errfile SYSLOG \
		-umask 027 \
		-user unifi \
		-Dunifi.datadir=/var/lib/unifi \
		-Dunifi.logdir=/var/log/unifi \
		-Dunifi.rundir=/run/unifi \
		-Dunifi.core.enabled=false \
		-Xmx1024M \
		-Djava.awt.headless=true \
		-Dfile.encoding=UTF-8 \
		com.ubnt.ace.Launcher start
	wait_for_pid created "$PIDFILE"
	check_status
}

stop() {
	log_stop "$NAME"
	$EXEC \
		-cwd /usr/lib/unifi \
		-home /opt/java \
		-cp /opt/commons-daemon/commons-daemon.jar:/usr/lib/unifi/lib/ace.jar \
		-pidfile $PIDFILE \
		-procname unifi \
		-outfile SYSLOG \
		-errfile SYSLOG \
		-umask 027 \
		-user unifi \
		-Dunifi.datadir=/var/lib/unifi \
		-Dunifi.logdir=/var/log/unifi \
		-Dunifi.rundir=/run/unifi \
		-Dunifi.core.enabled=false \
		-Xmx1024M \
		-Djava.awt.headless=true \
		-Dfile.encoding=UTF-8 \
		-stop com.ubnt.ace.Launcher stop
	wait_for_stop
	check_status
}

restart() {
	stop
	sleep 1
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}" >&2
	exit 1
	;;
esac
